name: Check compose files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup docker
        uses: docker/setup-buildx-action@v3

      - name: Check compose files
        run: |
          find . -type f -name "compose.yaml" | while read -r compose_file; do
            dir=$(dirname "$compose_file")
            echo "Executing 'docker compose config' in directory: $dir"

            (cd "$dir" && docker compose config)

            echo "-----------------------------"
          done
